{
 "title": "AWS CloudWatch Logs",
 "description": "Visualize AWS CloudWatch logs metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "loggroupname",
    "label": "LogGroupName",
    "query": "dimension_values($region, AWS/Logs, IncomingBytes, LogGroupName)"
   }
  ]
 },
 "panels": [
  {
   "title": "IncomingBytes/ForwardedBytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LogGroupName": "$loggroupname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "IncomingBytes",
     "namespace": "AWS/Logs",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LogGroupName": "$loggroupname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ForwardedBytes",
     "namespace": "AWS/Logs",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "IncomingLogEvents/ForwardedLogEvents",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LogGroupName": "$loggroupname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "IncomingLogEvents",
     "namespace": "AWS/Logs",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LogGroupName": "$loggroupname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ForwardedLogEvents",
     "namespace": "AWS/Logs",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "DeliveryErrors/DeliveryThrottling",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LogGroupName": "$loggroupname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DeliveryErrors",
     "namespace": "AWS/Logs",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LogGroupName": "$loggroupname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DeliveryThrottling",
     "namespace": "AWS/Logs",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}